config/routes.rb
require 'subdomain'

Programkina::Application.routes.draw do
  
  get "dashboard" => "dashboard#index", :as => :dashboard
  post "set_notification" => "dashboard#set_notification"
  get "clear_notification" => "dashboard#clear_notification"
  
  get "settings" => "account#edit", :as => :edit_settings
  put "settings" => "account#update", :as => :update_settings
  
  get "scripts(/:subaction)" => "scripts#index", :as => :scripts

  devise_for :users do
    get "/sign_in" => "devise/sessions#new", :as => :sign_in
    get "/sign_out" => "devise/sessions#destroy", :as => :sign_out
    get "/sign_up" => "devise/registrations#new", :as => :sign_up
  end

  resources :stages do
    resources :events
    member do
      delete 'remove_all_events'
    end
  end

  resources :sections do
    member do
      get 'events'
      get 'add_events'
      post 'add_event/:event_id' => "sections#add_event", as: :add_event
      delete 'remove_event/:event_id' => "sections#remove_event", as: :remove_event
      delete 'remove_all_events'
    end
  end

  resources :events
  
  scope "(:context)", :context => /embed/ do
    constraints(Subdomain) do  
      match '/' => "jqm#index", :as => :jqm_root
      match 'stage/:id' => "jqm#stage", :as => :jqm_stage
      match 'section/:id' => "jqm#section", :as => :jqm_section
      get 'day/:date(/:stage)' => "jqm#day", :as => :jqm_day
      get 'event/:id' => "jqm#detail", :as => :jqm_event
      match 'search' => "jqm#search", :as => :jqm_search
    end
  end
  
  get '/contact' => "public#contact", :as => :public_contact

  match '/pebble/:provider_id' => "public#pebble", :as => :pebble
 

  
  root :to => "public#index"

end

app/models/section.rb
class Section < ActiveRecord::Base
  
  belongs_to :user
  has_many :events

  attr_accessible :name

end

app/controllers/sections_controller.rb
#encoding: utf-8

class SectionsController < ApplicationController
  
  load_and_authorize_resource

  # GET /sections
  # GET /sections.json
  def index
    @sections = current_user.sections

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sections }
    end
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
    @section = Section.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @section }
    end
  end

  # GET /sections/new
  # GET /sections/new.json
  def new
    @section = Section.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @section }
    end
  end

  # GET /sections/1/edit
  def edit
    @section = Section.find(params[:id])
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(params[:section])
    @section.user_id = current_user.id

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Sekcia bola vytvorená.' }
        format.json { render json: @section, status: :created, location: @section }
      else
        format.html { render action: "new" }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sections/1
  # PUT /sections/1.json
  def update
    @section = Section.find(params[:id])

    respond_to do |format|
      if @section.update_attributes(params[:section])
        format.html { redirect_to @section, notice: 'Sekcia bola upravená.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section = Section.find(params[:id])
    @section.destroy

    respond_to do |format|
      format.html { redirect_to sections_url, notice: "Sekcia bola vymazaná." }
      format.json { head :no_content }
      format.js { render nothing: true, status: 200 }
    end
  end

  # GET /sections/1/add_events
  def add_events
    @events = Event.where('section_id != ? OR section_id IS NULL', params[:id])
  end

  # POST /sections/1/add_event/1
  def add_event
    @section.events << Event.find_by_id(params[:event_id])

    respond_to do |format|
      format.html { redirect_to sections_url, notice: "Predstavenie bolo pridané do sekcie." }
      format.json { head :no_content }
      format.js { render nothing: true, status: 200 }
    end
  end

  def remove_event
    @section.events.delete(Event.find_by_id(params[:event_id]))
    
    respond_to do |format|
      format.html { redirect_to sections_url, notice: "Predstavenie bolo odstránené zo sekcie." }
      format.json { head :no_content }
      format.js { render nothing: true, status: 200 }
    end
  end

  def remove_all_events
    @section = Section.find(params[:id])
    @section.events.clear    
    respond_to do |format|
      format.html { redirect_to events_section_path(@section), notice: "Všetky predstavenia v tejto sekcii boli vymazané." }
      format.json { head :no_content }
    end
  end

  def events
    @events = @section.events
  end
end

app/views/sections/_form.html.erb
<%= render 'shared/form_errors', target: @section %>

<%= form_for(@section) do |f| %>
  <div class="field">
    <%= f.label :name, "Názov" %><br />
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit "Uložiť" %>
  </div>
<% end %>

app/views/sections/add_events.html.erb
<h2>Pridať predstavenia do sekcie: <%= @section.name %></h2>

<div class="above-table">
  <h3>Predstavenia</h3>
</div>

<% if @events.any? %>
  
<table cellpadding="0" cellspacing="0" width="100%" class="sortable" id="stages-list">
  <tr>
    <th>Názov</th>
    <th></th>
  </tr>

  <% @events.each do |event| %>
    <tr class="<%= cycle("even","odd") %>" data-event-id="<%= event.id %>">
      <td><%= event.title %></td>
      <td>
        <%= link_to 'Pridať do sekcie', add_event_section_path(@section, event.id), method: :post, remote: true, class: 'add-event' %>
      </td>
    </tr>
  <% end %>
</table>

<% else %>

  <p>Žiadne predstavenia, ktoré by sa ešte dali pridať do tejto sekcie.</p>

<% end %>

app/views/sections/edit.html.erb
<h2>Upraviť sekciu</h2>

<%= render 'form' %>

<%= link_to 'Zobraziť', @section %> |
<%= link_to 'Späť', sections_path %>

app/views/sections/events.html.erb
<h2>Správa programu sekcie: <%= @section.name %></h2>

<div class="above-table">
  <h3>Predstavenia</h3>
  <%= link_to "Pridať predstavenie", add_events_section_path(@section), :class=>"bigbutton" %>
</div>

<% if @section.events.any? %>
  
<table cellpadding="0" cellspacing="0" width="100%" class="sortable" id="stages-list">
  <tr>
    <th>Názov</th>
    <th></th>
  </tr>

  <% @section.events.each do |event| %>
    <tr class="<%= cycle("even","odd") %>" data-event-id="<%= event.id %>">
      <td><%= event.title %></td>
      <td>
        <%= link_to 'Zobraziť detaily', stage_event_path(event.stage, event) %>
        <%= link_to 'Upraviť', edit_stage_event_path(event.stage, event) %>
        <%= link_to 'Odstrániť zo sekcie', remove_event_section_path(@section, event), confirm: 'Naozaj chcete toto predstavenie odstrániť zo sekcie?', method: :delete, remote: true, class: 'remove-event' %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to "Odstrániť zo sekcie všetky predstavenia", remove_all_events_section_path(@section), confirm: "Naozaj chcete zo sekcie odstrániť všetky predstavenia?", method: :delete %>

<% else %>

  <p>Žiadne predstavenia v tejto sekcii.</p>

<% end %>

app/views/sections/index.html.erb
<h2>Sekcie</h2>

<table cellpadding="0" cellspacing="0" width="100%" class="sortable" id="sections-list">
  <tr>
    <th>Názov</th>
    <th></th>
  </tr>

<% @sections.each do |section| %>
  <tr class="<%= cycle("even","odd") %>">
    <td><%= section.name %></td>
    <td>
      <%= link_to 'Zobraziť detaily', section %>
      <%= link_to 'Upraviť', edit_section_path(section) %>
      <%= link_to 'Zmazať', section, confirm: 'Naozaj chcete nevratne zmazať túto sekciu?', method: :delete, remote: true, class: 'remove-section' %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Pridať sekciu', new_section_path %>

app/views/sections/new.html.erb
<h2>Pridať sekciu</h2>

<%= render 'form' %>

<%= link_to 'Späť', sections_path %>

app/views/sections/show.html.erb
<h3><%= @section.name %></h3>

<%= link_to 'Upraviť', edit_section_path(@section) %> |
<%= link_to 'Vymazať', section_path(@section), method: :delete %> |
<%= link_to 'Späť', sections_path %>