config/routes.rb
require 'subdomain'

Programkina::Application.routes.draw do
  
  get "dashboard" => "dashboard#index", :as => :dashboard
  post "set_notification" => "dashboard#set_notification"
  get "clear_notification" => "dashboard#clear_notification"
  
  get "settings" => "account#edit", :as => :edit_settings
  put "settings" => "account#update", :as => :update_settings
  
  get "scripts(/:subaction)" => "scripts#index", :as => :scripts

  devise_for :users do
    get "/sign_in" => "devise/sessions#new", :as => :sign_in
    get "/sign_out" => "devise/sessions#destroy", :as => :sign_out
    get "/sign_up" => "devise/registrations#new", :as => :sign_up
  end

  resources :stages do
    resources :events
    member do
      delete 'remove_all_events'
    end
  end

  resources :sections do
    member do
      get 'events'
      get 'add_events'
      post 'add_event/:event_id' => "sections#add_event", as: :add_event
      delete 'remove_event/:event_id' => "sections#remove_event", as: :remove_event
      delete 'remove_all_events'
    end
  end

  resources :events
  
  scope "(:context)", :context => /embed/ do
    constraints(Subdomain) do  
      match '/' => "jqm#index", :as => :jqm_root
      match 'stage/:id' => "jqm#stage", :as => :jqm_stage
      match 'section/:id' => "jqm#section", :as => :jqm_section
      get 'day/:date(/:stage)' => "jqm#day", :as => :jqm_day
      get 'event/:id' => "jqm#detail", :as => :jqm_event
      match 'search' => "jqm#search", :as => :jqm_search
    end
  end
  
  get '/contact' => "public#contact", :as => :public_contact

  match '/pebble/:provider_id' => "public#pebble", :as => :pebble
 

  
  root :to => "public#index"

end

app/controllers/jqm_controller.rb
#encoding: utf-8

class JqmController < ApplicationController
  layout "jqm"
  
  before_filter :find_provider
  
  def index
    @stages = @provider.user.stages
    @sections = @provider.user.sections.order(:name)
    if @provider.theater?
      render :index_theater
    elsif @provider.festival?
      @days = @provider.festival_days
      render :index_festival
    end
  end
  
  def stage
    @stage = Stage.find_by_id(params[:id])
    
    #@events = EventDate.where("date>'#{now}'").group(:event_id).map {|ed| ed.event }
    
    if @stage.nil? || @stage.user != @provider.user
      flash[:notice] = "Neznáma sála :("
      render :not_found
    else
      @dates = EventDate.where("datetime>:now AND stage_id=:stage_id", {
        :now => Time.now,
        :stage_id => @stage.id
      }).group(:date)
    end
  end

  def section
    @section = Section.find_by_id(params[:id])
    
    if @section.nil? || @section.user != @provider.user
      flash[:notice] = "Neznáma sekcia :("
      render :not_found
    else
      @dates = EventDate.where("datetime>:now AND event_id IN (:events)", {
        :now => Time.now,
        :events => @section.events
      }).group(:date)
    end
  end
  
  def day
    @provider_stages = @provider.user.stages
    
    stages = @provider_stages.clone
    unless params[:stage].blank?
      @selected_stage_id = params[:stage].to_i
      stages.select!{ |s| s.id == @selected_stage_id }
    end
    
    @event_dates = EventDate.where('stage_id IN (?) AND date=?', stages, params[:date]).group(:datetime).order(:datetime)
    if @event_dates.empty?
      flash[:notice] = "Nič na programe :("
      render :not_found
    end
  end

  def detail
    @event = Event.find_by_id(params[:id])
    if @event
      @show_back_button = true
      render :detail
    else
      flash[:notice] = "Predstavenie sa nenašlo :("
      render :not_found
    end
  end
  
  def search
    @query = params[:search]
    redirect_to jqm_root_path if @query.blank?
    @events = Event.where("title LIKE '%#{@query}%' OR orig_title LIKE '%#{@query}%'")
  end
  
  private
  
    def find_provider
      @provider = Account.find_by_subdomain(request.subdomain)
      if @provider.nil?
        flash[:notice] = "Na subdoméne '#{request.subdomain}.programkina.sk' nič nie je :( <br /> Žeby preklep?".html_safe
        render :not_found
      end
    end
end

app/helpers/jqm_helper.rb
#encoding: utf-8

module JqmHelper
  
  def event_times(event, date)
    times = event.event_dates.where(:date => date).collect do |ed|
      ed.datetime.strftime('%H:%M')
    end
    times.join(', ')
  end
  
  def fancy_account_type
    case @provider.account_type
    when Account::TYPE_THEATER
      "kino"
    when Account::TYPE_FESTIVAL
      "festival"
    end
  end
end

app/views/jqm/day.html.erb
<% content_for :header do %>
  <div class="ui-bar ui-bar-b">
    <h2><%= formated_date(@event_dates.first.date) %></h2>
    <div style="position:absolute;right:5px;top:0;">
      <%= select_tag "stage_filter", options_for_select(@provider_stages.map{|s| [s.name, s.id]}, params[:stage]), :prompt => "Všetky sály", 'data-theme' => 'e' %>
    </div>
  </div>
<% end %>

<ul data-role="listview" data-filter="true" data-filter-placeholder="Hľadať film podľa názvu..." data-theme="a" data-divider-theme="d">
  <% @event_dates.each do |ed| %>
    <li data-role="list-divider"><%= ed.datetime.strftime("%H:%M") %></li>
    <% ed.events_on_datetime(@selected_stage_id).each do |event| %>
    <li>
      <a href="<%= jqm_event_path(event) %>" title="Detaily predstavenia">
        <h3><%= event.title %></h3>
        <% unless event.orig_title.blank? %>
        <p><strong><%= event.orig_title %></strong></p>
        <% end %>
        <% unless event.section.nil?  %>
        <p>[Sekcia<strong> <%= event.section.name %></strong>]</p>
        <% end %>
        <% unless event.info.blank? %>
        <p><%= event.info %></p>
        <% end %>
        <p class="ui-li-aside"><strong><%= event.stage.name %></strong></p>
      </a>
    </li>
    <% end %>
  <% end %>
</ul>

<script type="text/javascript">
  $('#stage_filter').change(function(){
    var stage_id = $(this).val();
    var redirect_url = '<%= jqm_day_url(params[:date]) %>';
    if (stage_id!=='') {
      redirect_url += '/' + stage_id;
    }
    window.location.href = redirect_url;
  });
</script>

app/views/jqm/detail.html.erb
<% content_for :header do %>
  <div class="ui-bar ui-bar-b">
    <h2><%= @event.stage.name %></h2>
  </div>
<% end %>

<div class="ui-body ui-body-c">
  <h2><%= @event.title %></h2>
  <% if @event.orig_title %>
    <p><em><%= @event.orig_title %></em></p>
  <% end %>
  <% unless @event.section.nil?  %>
    <p><strong>Sekcia:</strong> <%= @event.section.name %></p>
  <% end %>
  <p><%= simple_format(@event.description) %></p>
  <p>Typ predstavenia: <%= @event.event_type %></p>
  <p><%= simple_format(@event.info) %></p>
  
  <ul data-role="listview" data-inset="true" data-dividertheme="b">
    <li data-role="list-divider">Premietania</li>
    <% @event.event_dates.each do |ed| %>
    <li><%= weekday(ed.datetime) %> <%= ed.datetime.strftime("%d.%m.%Y o %H:%M") %> - <%= ed.event.stage.name %></li>
    <% end %>
  </ul>

  <% unless @event.poster.blank? %>
    <div data-role="collapsible" data-theme="a" id="event-poster-container">
      <h3>Obrázok k filmu</h3>
      <p><img src="<%= @event.poster.html_safe %>" alt="Poster" class="event-poster" /></p>
    </div>
  <% end %>

  <% unless @event.trailer.blank? %>
    <div data-role="collapsible" data-theme="a">
      <h3>Trailer k filmu</h3>
      <iframe width="240" height="152" src="http://www.youtube.com/embed/<%= @event.trailer.html_safe %>" frameborder="0" allowfullscreen></iframe>
    </div>
  <% end %>
</div>

<script>
$('#event-poster-container').on('expand',function(){
  var $poster = $(this).find('img.event-poster');
  var $wrapper = $poster.parent();
  setTimeout(function(){
    if ($poster.width() > $wrapper.width()) {
      $poster.width($wrapper.width());
    }
  }, 100);
});
</script>

app/views/jqm/index.html.erb
<h3>Vyberte si javisko</h3>
<ul data-role="listview" data-inset="true">
  <% @stages.each do |s| %>
  <li>
    <%= link_to s.name, jqm_stage_path(s) %>
  </li>
  <% end %>
</ul>

app/views/jqm/index_festival.html.erb
<% unless controller.is_embed? %>
<div class="festival-logo" style="margin:-15px -15px 0 -15px; text-align:center; background:#000;">
  <img src="<%= image_path('cinematik2013.png') %>" alt="Logo">
</div>
<% end %>

<%= form_tag jqm_search_url, method: :post do %>
  <div data-role="fieldcontain" class="ui-hide-label">
    <label for="search">Hľadať film podľa názvu:</label>
    <input type="search" name="search" id="search" value="" data-mini="true" placeholder="Hľadať film podľa názvu..." />
  </div>
<% end %>

<h3><center>Vyberte si deň</center></h3>

<ul data-role="listview" data-inset="true">
  <% @days.each do |d| %>
  <li>
    <%= link_to formated_date(d.date), jqm_day_path(d.date) %>
  </li>
  <% end %>
</ul>

<h3><center>Vyberte si sálu</center></h3>

<ul data-role="listview" data-inset="true">
  <% @stages.each do |s| %>
  <li>
    <%= link_to s.name, jqm_stage_path(s) %>
  </li>
  <% end %>
</ul>

<% if @sections.any? %>
  <h3><center>Sekcie</center></h3>

  <ul data-role="listview" data-inset="true">
    <% @sections.each do |s| %>
    <li>
      <%= link_to s.name, jqm_section_path(s) %>
    </li>
    <% end %>
  </ul>
<% end %>

app/views/jqm/index_theater.html.erb
<h3>Vyberte si sálu</h3>

<ul data-role="listview" data-inset="true">
  <% @stages.each do |s| %>
  <li>
    <%= link_to s.name, jqm_stage_path(s) %>
  </li>
  <% end %>
</ul>

app/views/jqm/not_found.html.erb
<div class="ui-body ui-body-c">
  <h2>Chyba</h2>
  <p><%= flash[:notice] %></p>
</div>

app/views/jqm/search.html.erb
<% content_for :header do %>
  <div class="ui-bar ui-bar-b">
    <h2>Vyhľadávanie: <em style="font-weight:normal;"><%= @query %></em></h2>
  </div>
<% end %>

<% unless @events.empty? %>

<ul data-role="listview" data-theme="a">
  <% @events.each do |event| %>
    <li>
      <a href="<%= jqm_event_path(event) %>" title="Detaily predstavenia">
        <h3><%= event.title %></h3>
        <% unless event.orig_title.blank? %>
        <p><strong><%= event.orig_title %></strong></p>
        <% end %>
        <% unless event.info.blank? %>
        <p><%= event.info %></p>
        <% end %>
        <p class="ui-li-aside"><strong><%= event.stage.name %></strong></p>
      </a>
    </li>
  <% end %>
</ul>

<% else %>

<p>Žiadne vyhovujúce predstavenia sa nenašli :(</p>

<% end %>

app/views/jqm/section.html.erb
<% content_for :header do %>
  <div class="ui-bar ui-bar-b">
    <h2>Sekcia: <%= @section.name %></h2>
  </div>
<% end %>

<ul data-role="listview" data-filter="true" data-filter-placeholder="Hľadať film podľa názvu..." data-theme="a" data-divider-theme="d">
  <% @dates.each do |d| %>
  <li data-role="list-divider"><%= weekday(d.datetime) %>, <%= d.datetime.strftime("%d.%m.%Y") %></li>
    <% d.events_on_date_and_section(@section).each do |event| %>
    <li>
      <a href="<%= jqm_event_path(event) %>" title="Detaily predstavenia">
        <h3><%= event.title %></h3>
        <% unless event.orig_title.blank? %>
        <p><strong><%= event.orig_title %></strong></p>
        <% end %>
        <% unless event.section.nil?  %>
        <p>[Sála <strong><%= event.stage.name %></strong>]</p>
        <% end %>
        <% unless event.info.blank? %>
        <p><%= event.info %></p>
        <% end %>
        <p class="ui-li-aside"><strong><%= event_times(event, d.date) %></strong></p>
      </a>
    </li>
    <% end %>
  <% end %>
</ul>

app/views/jqm/stage.html.erb
<% content_for :header do %>
  <div class="ui-bar ui-bar-b">
    <h2>Program pre sálu: <%= @stage.name %></h2>
  </div>
<% end %>

<ul data-role="listview" data-filter="true" data-filter-placeholder="Hľadať film podľa názvu..." data-theme="a" data-divider-theme="d">
  <% @dates.each do |d| %>
  <li data-role="list-divider"><%= weekday(d.datetime) %>, <%= d.datetime.strftime("%d.%m.%Y") %></li>
    <% d.events_on_date_and_stage.each do |event| %>
    <li>
      <a href="<%= jqm_event_path(event) %>" title="Detaily predstavenia">
        <h3><%= event.title %></h3>
        <% unless event.orig_title.blank? %>
        <p><strong><%= event.orig_title %></strong></p>
        <% end %>
        <% unless event.section.nil?  %>
        <p>[Sekcia <strong><%= event.section.name %></strong>]</p>
        <% end %>
        <% unless event.info.blank? %>
        <p><%= event.info %></p>
        <% end %>
        <p class="ui-li-aside"><strong><%= event_times(event, d.date) %></strong></p>
      </a>
    </li>
    <% end %>
  <% end %>
</ul>