config/routes.rb
require 'subdomain'

Programkina::Application.routes.draw do
  
  get "dashboard" => "dashboard#index", :as => :dashboard
  post "set_notification" => "dashboard#set_notification"
  get "clear_notification" => "dashboard#clear_notification"
  
  get "settings" => "account#edit", :as => :edit_settings
  put "settings" => "account#update", :as => :update_settings
  
  get "scripts(/:subaction)" => "scripts#index", :as => :scripts

  devise_for :users do
    get "/sign_in" => "devise/sessions#new", :as => :sign_in
    get "/sign_out" => "devise/sessions#destroy", :as => :sign_out
    get "/sign_up" => "devise/registrations#new", :as => :sign_up
  end

  resources :stages do
    resources :events
    member do
      delete 'remove_all_events'
    end
  end

  resources :sections do
    member do
      get 'events'
      get 'add_events'
      post 'add_event/:event_id' => "sections#add_event", as: :add_event
      delete 'remove_event/:event_id' => "sections#remove_event", as: :remove_event
      delete 'remove_all_events'
    end
  end

  resources :events
  
  scope "(:context)", :context => /embed/ do
    constraints(Subdomain) do  
      match '/' => "jqm#index", :as => :jqm_root
      match 'stage/:id' => "jqm#stage", :as => :jqm_stage
      match 'section/:id' => "jqm#section", :as => :jqm_section
      get 'day/:date(/:stage)' => "jqm#day", :as => :jqm_day
      get 'event/:id' => "jqm#detail", :as => :jqm_event
      match 'search' => "jqm#search", :as => :jqm_search
    end
  end
  
  get '/contact' => "public#contact", :as => :public_contact

  match '/pebble/:provider_id' => "public#pebble", :as => :pebble
 

  
  root :to => "public#index"

end

app/models/stage.rb
class Stage < ActiveRecord::Base
  
  belongs_to :user
  has_many :events, dependent: :destroy

  attr_accessible :name

end

app/controllers/stages_controller.rb
#encoding: utf-8

class StagesController < ApplicationController
  
  load_and_authorize_resource

  # GET /stages
  # GET /stages.json
  def index
    @stages = current_user.stages

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stages }
    end
  end

  # GET /stages/1
  # GET /stages/1.json
  def show
    @stage = Stage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stage }
    end
  end

  # GET /stages/new
  # GET /stages/new.json
  def new
    @stage = Stage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stage }
    end
  end

  # GET /stages/1/edit
  def edit
    @stage = Stage.find(params[:id])
  end

  # POST /stages
  # POST /stages.json
  def create
    @stage = Stage.new(params[:stage])
    @stage.user_id = current_user.id

    respond_to do |format|
      if @stage.save
        format.html { redirect_to @stage, notice: 'Stage was successfully created.' }
        format.json { render json: @stage, status: :created, location: @stage }
      else
        format.html { render action: "new" }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stages/1
  # PUT /stages/1.json
  def update
    @stage = Stage.find(params[:id])

    respond_to do |format|
      if @stage.update_attributes(params[:stage])
        format.html { redirect_to @stage, notice: 'Sála bola upravená.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stages/1
  # DELETE /stages/1.json
  def destroy
    @stage = Stage.find(params[:id])
    @stage.destroy

    respond_to do |format|
      format.html { redirect_to stages_url, notice: 'Sála bola vymazaná.' }
      format.json { head :no_content }
    end
  end

  def remove_all_events
    @stage = Stage.find(params[:id])
    @stage.events.destroy_all
    
    respond_to do |format|
      format.html { redirect_to stage_events_path(@stage), notice: "Všetky predstavenia v tejto scéne boli vymazané." }
      format.json { head :no_content }
    end
  end
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/_form.html.erb
<%= render 'shared/form_errors', target: @stage %>

<%= form_for(@stage) do |f| %>
  <div class="field">
    <%= f.label :name, "Názov" %><br />
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit "Uložiť" %>
  </div>
<% end %>

app/views/stages/edit.html.erb
<h2>Upraviť sálu</h2>

<%= render 'form' %>

<%= link_to 'Zobraziť', @stage %> |
<%= link_to 'Späť', stages_path %>

app/views/stages/index.html.erb
<h2>Sály</h2>

<table cellpadding="0" cellspacing="0" width="100%" class="sortable" id="stages-list">
  <tr>
    <th>Názov</th>
    <th></th>
  </tr>

<% @stages.each do |stage| %>
  <tr class="<%= cycle("even","odd") %>">
    <td><%= stage.name %></td>
    <td>
      <%= link_to 'Zobraziť detaily', stage %>
      <%= link_to 'Upraviť', edit_stage_path(stage) %>
      <%= link_to 'Zmazať', stage, confirm: 'Naozaj chcete nevratne zmazať túto sálu?', method: :delete %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Pridať sálu', new_stage_path %>

app/views/stages/new.html.erb
<h2>Pridať sálu</h2>

<%= render 'form' %>

<%= link_to 'Späť', stages_path %>

app/views/stages/show.html.erb
<h3><%= @stage.name %></h3>

<%= link_to 'Upraviť', edit_stage_path(@stage) %> |
<%= link_to 'Vymazať', stage_path(@stage), method: :delete %> |
<%= link_to 'Späť', stages_path %>