config/routes.rb
require 'subdomain'

Programkina::Application.routes.draw do
  
  get "dashboard" => "dashboard#index", :as => :dashboard
  post "set_notification" => "dashboard#set_notification"
  get "clear_notification" => "dashboard#clear_notification"
  
  get "settings" => "account#edit", :as => :edit_settings
  put "settings" => "account#update", :as => :update_settings
  
  get "scripts(/:subaction)" => "scripts#index", :as => :scripts

  devise_for :users do
    get "/sign_in" => "devise/sessions#new", :as => :sign_in
    get "/sign_out" => "devise/sessions#destroy", :as => :sign_out
    get "/sign_up" => "devise/registrations#new", :as => :sign_up
  end

  resources :stages do
    resources :events
    member do
      delete 'remove_all_events'
    end
  end

  resources :sections do
    member do
      get 'events'
      get 'add_events'
      post 'add_event/:event_id' => "sections#add_event", as: :add_event
      delete 'remove_event/:event_id' => "sections#remove_event", as: :remove_event
      delete 'remove_all_events'
    end
  end

  resources :events
  
  scope "(:context)", :context => /embed/ do
    constraints(Subdomain) do  
      match '/' => "jqm#index", :as => :jqm_root
      match 'stage/:id' => "jqm#stage", :as => :jqm_stage
      match 'section/:id' => "jqm#section", :as => :jqm_section
      get 'day/:date(/:stage)' => "jqm#day", :as => :jqm_day
      get 'event/:id' => "jqm#detail", :as => :jqm_event
      match 'search' => "jqm#search", :as => :jqm_search
    end
  end
  
  get '/contact' => "public#contact", :as => :public_contact

  match '/pebble/:provider_id' => "public#pebble", :as => :pebble
 

  
  root :to => "public#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <meta http-equiv="X-UA-Compatible" content="IE=7" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="description" content="." />
  <meta name="keywords" content="." />

  <title>ProgramKina.sk - <%= current_user.account.name %></title>

  <%= stylesheet_link_tag "application" %>

  <!--[if lt IE 9]>
  <%= stylesheet_link_tag "ie" %>
  <![endif]-->

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

  <div id="header">
    <h1><a href="<%= dashboard_path %>">ProgramKina.sk - <%= current_user.account.name %></a></h1>
    <% if user_signed_in? %>
      <div class="userprofile">
      <ul>
        <li><a href="#"><%= image_tag "/assets/avatar.gif" %> <%= current_user.email %></a>
          <ul>
            <li><%= link_to "Nastavenia účtu", edit_settings_path %></li>
            <li><%= link_to "Špeciálne skripty", scripts_path %></li>
            <li></li>
            <li><%= link_to "Odhlásiť sa", sign_out_path %></li>
          </ul>
        </li>
      </ul>
    </div>    <!-- .userprofile ends -->
    <% end %>
  </div>      <!-- #header ends -->

  <div id="sidebar">
    <ul id="nav">
      <li><%= main_menu_item_for dashboard_path, "Úvod", "Úvodná obrazovka", "dashboard.png" %></li>
      <li>
          <%= main_menu_item_for stages_path, "Sály", "Správa sál", "support.png" %>
          <ul>
          <% current_user.stages.order(:id).each do |stage| %>
            <li><%= main_menu_item_for stage_events_path(stage), stage.name, "Spravovať program", "calendar.png" %></li>
          <% end %>
          <% if current_user.stages.empty? %>
            <li><%= link_to 'Pridať sálu', new_stage_path %></li>
          <% end %>
          </ul>
      </li>
      <li>
          <%= main_menu_item_for sections_path, "Sekcie", "Správa sekcií", "support.png" %>
          <ul>
          <% current_user.sections.order(:id).each do |section| %>
            <li><%= main_menu_item_for events_section_path(section), section.name, "Spravovať program", "calendar.png" %></li>
          <% end %>
          <% if current_user.sections.empty? %>
            <li><%= link_to 'Pridať sekciu', new_section_path %></li>
          <% end %>
          </ul>
      </li>
    </ul>
  </div>

  <div id="content">

    <div class="breadcrumb">
      <%= link_to "Home", dashboard_path %>
    </div>

    <% if flash[:notice] %>
      <div class="message info" style="display: block;">
        <%= flash[:notice] %>
    <% end  %>
    <% if flash[:alert] %>
      <div class="message errormsg" style="display: block;">
        <%= flash[:alert] %>
    <% end %>
    <% if flash[:success] %>
      <div class="message sucess" style="display: block;">
        <%= flash[:success] %>
    <% end %>
    <% unless flash.empty? %>
        <span class="close" title="Dismiss"></span>
      </div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="X-UA-Compatible" content="IE=7" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="description" content="." />
	<meta name="keywords" content="." />

	<title>Kolkominate.sk</title>

  <%= stylesheet_link_tag "application" %>

	<!--[if lt IE 9]>
	<%= stylesheet_link_tag "ie" %>
	<![endif]-->

	<%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body class="loginpage">

	<div id="header">
		<h1><a href="#">Kolkominate.sk</a></h1>
	</div>			<!-- #header ends -->

	<div id="content" class="loginbox">
		<% if flash[:notice] %>
			<div class="message info" style="display: block;">
			  <%= flash[:notice] %>
		<% end  %>
		<% if flash[:alert] %>
			<div class="message errormsg" style="display: block;">
			  <%= flash[:alert] %>
		<% end %>
		<% if flash[:success] %>
			<div class="message sucess" style="display: block;">
			  <%= flash[:success] %>
		<% end %>
		<% unless flash.empty? %>
				<span class="close" title="Dismiss"></span>
			</div>
		<% end %>

	  <%= yield %>
	</div>

</body>
</html>

app/views/layouts/jqm.html.erb
<!DOCTYPE html>
<html lang="sk"> 
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    
    <title><%= @provider.name %></title>
    <meta name="description" content="Program pre <%= fancy_account_type %> <%= @provider.name %>">
    <meta name="keywords" content="program, kino, festival, program kina, program festivalu, <%= @provider.name %>">
    <meta name="author" content="Michal Valášek">
    <meta name="robots" content="all">
    
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.css" />
    <%= stylesheet_link_tag "cinematik" %>
    
    <link rel="apple-touch-icon" href="/images/touch-icon-iphone.jpg" />
    <link rel="apple-touch-icon" sizes="72x72" href="/images/touch-icon-ipad.jpg" />
    <link rel="apple-touch-icon" sizes="114x114" href="/images/touch-icon-iphone4.jpg" />
    <link rel="apple-touch-startup-image" href="<%= image_path('splashscreen.png') %>" />
    
    <script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.js"></script>
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-28833593-1']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
</head> 
 
<body>
  
  <div data-role="page" id="one">
    <div data-role="header">
      <%= link_to("Späť", "", 'data-rel'=>'back', 'data-icon'=>'arrow-l', 'data-theme'=>'d') if @show_back_button %>
      
      <h1 style="margin-left:auto;margin-right:auto;"><%= link_to (@provider.nil? ? "ProgramKina.sk" : @provider.name), jqm_root_path, {'data-role'=>"button", 'data-theme'=>"e", 'data-icon'=>"home", 'data-direction'=>"reverse"} %></h1>
      
      <%= yield :header %>
    </div>

    <div data-role="content">
      <%= yield %>
    </div>

    <div data-role="footer">
      <%= yield :footer %>
      <% if controller.is_embed? %>
        <h4>Interaktívny program od programkina.sk</h4>
        <p style="text-align:center;">Program dostupný aj pre mobily na <a href="http://cinematik.programkina.sk" title="Mobilná verzia programu">cinematik.programkina.sk</a></p>
      <% else %>
        <h4>App by ProgramKina.sk</h4>
      <% end %>
    </div>
  </div>
  
  <% unless @provider.notification.blank? %>
  <script type="text/javascript">
  $("<div class='ui-loader ui-overlay-shadow ui-body-a ui-corner-all'><h1>Upozornenie!</h1><h1><%= @provider.notification %></h1></div>")
    .css({ "display":"block", "opacity":0.96, "top": $(window).scrollTop() + 100 })
    .appendTo( $("body") )
    .delay(2500)
    .click(function(){
        $(this).remove();
    });
  </script>
  <% end %>
</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="description" content="Publikačná platforma pre mobilné programy kín a festivalov" />
  <meta name="keywords" content="kino festival mobil mobilný program webapp webaplikácia publikovanie" />
  <meta name="author" content="Michal Valášek">
  <meta name="robots" content="all">
  
  <title>ProgramKina.sk</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "public", :media => "all" %>
  <%= javascript_include_tag "public" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-28833593-1']);
    _gaq.push(['_trackPageview']);
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand" href="#">ProgramKina.sk</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Kontakt", public_contact_path %></li>
          </ul>
          <!-- NOT YET
          <p class="navbar-text pull-right">
            <%= link_to "Prihláste sa", sign_in_path %> alebo sa <%= link_to "zaregistrujte", sign_up_path %>
          </p>
           -->
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <%= yield %>
    
    <footer class="footer">
      <p>Created by <a href="http://michalvalasek.com" title="Home page">Michal Valášek</a> and <a href="http://q7.sk" title="Home page">Q7 Digital Media</a>, &copy;2012</p>
    </footer>
  </div>
</body>
</html>